version: '3.9'
services:
    api:
        build:
            context: ./makeitwork
        depends_on:
            - mysql
        ports:
            - 8000:80
        restart: always
        networks:
            - mnet
    mysql:
        image: mariadb:10.4.27
        restart: always
        command: --lower_case_table_names=1
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: Lab2021
            MYSQL_DATABASE: pets
            MYSQL_USER: Webuser
            MYSQL_PASSWORD: Lab2021
        ports:
            - "9906:3306"
        networks:
            - mnet
    # maui:
    #     build:
    #         context: ./phpmyadmin
    #     ports:
    #         - '8080:80'
    #     restart: always
    #     environment:
    #         PMA_HOST: mysql
    #     depends_on:
    #         - mysql
networks:
    mnet: